# Site settings
title: Wilson Junior - Programador
description: Blog de um desenvolvedor de software e apaixonado por tecnologia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.wilsonjunior.net" # the base hostname & protocol for your site

# User settings
username: Wilson Junior
tagline: Blog de Programação
user_description: Blog de um desenvolvedor de software e apaixonado por tecnologia.
email: contato@wilsonjunior.net
github_username:  wilsonjuniorwj
facebook_username: wilsonjunior.net
twitter_username: wilsonjuniorwj
linkedin_username: wilsonjuniorwj
disqus_username: wilsonjuniorwj
gplus_username: WilsonJunior0101

# Social Icons
github_icon: https://github.com/wilsonjuniorwj
earth_icon: https://wilsonjunior.net
envelope_icon: mailto:contato@wilsonjunior.net
linkedin_icon: https://www.linkedin.com/in/wilsonjuniorwj
rss-square_icon: https://blog.wilsonjunior.net/feed.xml

# Display links for the previous and next post on post pages.
display-next-prev-post: true
var_next_post: PRÓXIMO
var_previous_post: ANTERIOR

# website under construction
var_website_construction: false

# Google Analytics - Global Site Tag (gtag.js)
google-ID: 'UA-106774456-1'

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
# path: feed.xml

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 6

# plugins
plugins: [jekyll-paginate]

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

files_to_cache:
 - '/assets/js/blog.js'

pages_to_cache:
  - '/about/'
  - '/tags/'
  - '/offline/index.html'

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags/
  - title: Sobre
    url: /about/

# exclude my node related stuff
exclude: [
  'package.json',
  'src',
  'node_modules',
  'vendor/bundle/ruby',
  'package-lock.json',
  'README.md',
  'gulpfile.js',
  'initpost.sh',
  'testlinks.sh',
  '.travis.yml',
  'thumbnails/'
]

include: ['_redirects', '_headers']